name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:16

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: user1
          POSTGRES_DB: test_reddit
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Testing Routes
        run: npm test
        
        env:
          TEST_DB_URL: postgres://user1:password@postgres:5432/test_reddit
          NODE_ENV: test
